# .github/workflows/mangopi_m28c.yml
# 用于 GitHub Actions 云编译 MangoPi M28C 固件

name: Build OpenWrt for MangoPi_M28C

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            clang \
            flex \
            g++ \
            gawk \
            gcc-multilib \
            g++-multilib \
            gettext \
            git \
            libncurses-dev \
            libssl-dev \
            python3 \
            python3-pip \
            python3-apt \
            python3-venv \
            rsync \
            unzip \
            zlib1g-dev \
            file \
            wget

          pip3 install setuptools

      - name: Clone LEDE source
        run: |
          git clone https://github.com/coolsnowwolf/lede openwrt
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate default config for MangoPi M28C with plugins
        run: |
          cd openwrt
          cat >> .config <<EOF
          CONFIG_TARGET_rockchip=y
          CONFIG_TARGET_rockchip_rk3528=y
          CONFIG_TARGET_rockchip_rk3528_DEVICE_mangopi_m28c=y

          # 基础设置
          CONFIG_DEVEL=y
          CONFIG_BUILD_USER="github"
          CONFIG_BUILD_HOST="actions"

          # 插件参考 HinLink_H29K
          CONFIG_PACKAGE_luci=y
          CONFIG_PACKAGE_luci-app-upnp=y
          CONFIG_PACKAGE_luci-app-ddns=y
          CONFIG_PACKAGE_luci-app-wol=y
          CONFIG_PACKAGE_luci-app-ttyd=y
          CONFIG_PACKAGE_luci-app-aria2=y
          CONFIG_PACKAGE_luci-app-ssr-plus=y
          CONFIG_PACKAGE_luci-app-passwall=y
          CONFIG_PACKAGE_luci-app-v2ray-server=y
          CONFIG_PACKAGE_luci-app-turboacc=y
          CONFIG_PACKAGE_luci-app-unblockmusic=y
          CONFIG_PACKAGE_luci-app-adbyby-plus=y
          CONFIG_PACKAGE_luci-app-openclash=y
          CONFIG_PACKAGE_luci-app-diskman=y
          CONFIG_PACKAGE_luci-app-filebrowser=y
          CONFIG_PACKAGE_luci-app-smartdns=y
          CONFIG_PACKAGE_luci-app-zerotier=y

          # 5G模块支持（如 Quectel）相关插件
          CONFIG_PACKAGE_qmodem=y
          CONFIG_PACKAGE_chat=y
          CONFIG_PACKAGE_minicom=y
          CONFIG_PACKAGE_picocom=y
          CONFIG_PACKAGE_kmod-usb-serial=y
          CONFIG_PACKAGE_kmod-usb-serial-option=y
          CONFIG_PACKAGE_kmod-usb-serial-wwan=y
          CONFIG_PACKAGE_kmod-usb-net=y
          CONFIG_PACKAGE_kmod-usb-net-cdc-ether=y
          CONFIG_PACKAGE_kmod-usb-net-rndis=y
          CONFIG_PACKAGE_kmod-usb-net-qmi-wwan=y
          CONFIG_PACKAGE_kmod-usb-wdm=y
          CONFIG_PACKAGE_wwan=y
          CONFIG_PACKAGE_luci-proto-qmi=y
          CONFIG_PACKAGE_luci-proto-wwan=y
          CONFIG_PACKAGE_luci-proto-ncm=y

          # 可选 Watchdog、网络保持工具
          CONFIG_PACKAGE_watchcat=y
          CONFIG_PACKAGE_relayd=y
          CONFIG_PACKAGE_umbim=y
          CONFIG_PACKAGE_luci-proto-mbim=y

          # 启动项脚本和自动拨号配置支持
          CONFIG_PACKAGE_rc=y
          CONFIG_PACKAGE_qmodem-autostart=y
          CONFIG_PACKAGE_cron=y
          CONFIG_PACKAGE_luci-app-scheduled-reboot=y

          EOF

          make defconfig

      - name: Build OpenWrt
        run: |
          cd openwrt
          make -j$(nproc) download
          make -j$(nproc) V=s

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: MangoPi_M28C_Firmware
          path: openwrt/bin/targets/*/*
